Action({
  Execute: async (session, ctx, args) => 'ok',
  Args: {
    OldDOB: { field: 'DOB' },
    NewDOB: { domain: 'DateTime' },
    LastName: { field: 'FullName.LastName' },
  },
  Returns: {
    NewDOB: { domain: 'DateTime' },
  },
})
